#!/bin/zsh

set -e
# set -v

scriptPath="$(pwd)"
sourceFile="${1%.*}"
gdbPort=$(cat $(dirname $0)/.gdb-port)

$scriptPath/.vscode/build $1

echo "Attaching to remote debugger for $sourceFile on port $gdbPort..."
gdb-multiarch -q --nh -ex "file $sourceFile" -ex "target remote localhost:$gdbPort"
