#!/bin/zsh

set -e
# set -v

scriptPath="$(pwd)"
sourceFile="${1%.*}"
gdbPort=$(cat $(dirname $0)/.gdb-port)

echo "Starting in $sourceFile in debug mode on port $gdbPort..."
qemu-aarch64-static -g $gdbPort $sourceFile
